; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F401RC]
platform = ststm32
board = genericSTM32F401RC
framework = libopencm3
board_build.mcu = stm32f401rct6
board_build.f_cpu = 84000000L

upload_protocol = stlink

lib_deps =
	file://lib/yaudio_libs/libogg-1.3.6
	file://lib/yaudio_libs/opus-1.5.2
	file://lib/yaudio_libs/opusfile-0.12
	file://lib/yaudio_libs/dr_libs-wav-0.14.2

build_flags = -Wl,-Map,output.map
	-Ilib/sd-spi-driver/inc
	-Ilib/yaudio_libs/libogg-1.3.6/include
	-Ilib/yaudio_libs/opus-1.5.2/include
	-Ilib/yaudio_libs/opus-1.5.2/include/opus
	-Ilib/yaudio_libs/opusfile-0.12/include
	-Llib/yaudio_libs/libogg-1.3.6/lib
	-Llib/yaudio_libs/opus-1.5.2/lib
	-Llib/yaudio_libs/opusfile-0.12/lib
	-logg
	-lopus
	-lopusfile
	-Ilib/yaudio_libs/dr_libs-wav-0.14.2
